wib python 3.13

diff --git a/rust/docker/Dockerfile.static_musl_app b/rust/docker/Dockerfile.static_musl_app
--- a/rust/docker/Dockerfile.static_musl_app
+++ b/rust/docker/Dockerfile.static_musl_app
@@ -141,7 +141,7 @@ RUN cd /rust-photoacoustic/rust && \
     ln -svf /usr/bin/strip /usr/bin/arm-linux-musleabihf-strip && \
     ln -svf /usr/bin/ranlib /usr/bin/arm-linux-musleabihf-ranlib && \
     echo "armv7-unknown-linux-musleabihf" > _target && \
-    LDFLAGS="-static -L/usr/local/lib -L/usr/local/lib64" RUSTFLAGS="-C target-feature=+crt-static -L /usr/local/lib -L /usr/local/lib64 -l static=readline -l static=history -l static=termcap -l static=mimalloc -l static=python$PYTHON_SHORT_VERSION -l static=rdkafka -l static=ssl -l static=crypto" CARGO_CFG_TARGET_FEATURE="+crt-static" cargo build --release --target armv7-unknown-linux-musleabihf && \
+    LDFLAGS="-static -L/usr/local/lib" RUSTFLAGS="-C target-feature=+crt-static -L /usr/local/lib -l static=intl -l static=readline -l static=history -l static=termcap -l static=python$PYTHON_SHORT_VERSION -l static=rdkafka -l static=ssl -l static=crypto" CARGO_CFG_TARGET_FEATURE="+crt-static" cargo build --release --target armv7-unknown-linux-musleabihf && \
     echo "Build completed successfully for armv7l" && \
     ls -la target/armv7-unknown-linux-musleabihf/release/ || true; \
     elif [ "$(uname -m)" = "aarch64" ]; then \
@@ -151,38 +151,39 @@ RUN cd /rust-photoacoustic/rust && \
     ln -svf /usr/bin/strip /usr/bin/aarch64-linux-musl-strip && \
     ln -svf /usr/bin/ranlib /usr/bin/aarch64-linux-musl-ranlib && \
     echo "aarch64-unknown-linux-musl" > _target && \
-    LDFLAGS="-static -L/usr/local/lib -L/usr/local/lib64" RUSTFLAGS="-C target-feature=+crt-static -L /usr/local/lib -L /usr/local/lib64 -l static=readline -l static=history -l static=termcap -l static=mimalloc -l static=python$PYTHON_SHORT_VERSION -l static=rdkafka -l static=ssl -l static=crypto" CARGO_CFG_TARGET_FEATURE="+crt-static" cargo build --release --target aarch64-unknown-linux-musl && \
+    LDFLAGS="-static -L/usr/local/lib" RUSTFLAGS="-C target-feature=+crt-static -L /usr/local/lib -l static=intl -l static=readline -l static=history -l static=termcap -l static=python$PYTHON_SHORT_VERSION -l static=rdkafka -l static=ssl -l static=crypto" CARGO_CFG_TARGET_FEATURE="+crt-static" cargo build --release --target aarch64-unknown-linux-musl && \
     echo "Build completed successfully for aarch64" && \
     ls -la target/aarch64-unknown-linux-musl/release/ || true; \
     elif [ "$(uname -m)" = "x86_64" ]; then \
     echo "Building for x86_64 architecture" && \
     . /root/.cargo/env && rustup target add x86_64-unknown-linux-musl && \
     echo "x86_64-unknown-linux-musl" > _target && \
-    LDFLAGS="-static -L/usr/local/lib -L/usr/local/lib64" RUSTFLAGS="-C target-feature=+crt-static -L /usr/local/lib -L /usr/local/lib64 -l static=readline -l static=history -l static=termcap -l static=mimalloc -l static=python$PYTHON_SHORT_VERSION -l static=rdkafka -l static=ssl -l static=crypto" CARGO_CFG_TARGET_FEATURE="+crt-static" cargo build --release --target x86_64-unknown-linux-musl && \
+    echo "NEED TO REMOVE TRUE BEFORE FINAL BUILD" && \
+    LDFLAGS="-static -L/usr/local/lib" RUSTFLAGS="-C target-feature=+crt-static -L /usr/local/lib -l static=intl -l static=readline -l static=history -l static=termcap -l static=python$PYTHON_SHORT_VERSION -l static=rdkafka -l static=ssl -l static=crypto" CARGO_CFG_TARGET_FEATURE="+crt-static" cargo build --release --target x86_64-unknown-linux-musl || true && \
     echo "Build completed successfully for x86_64" && \
     ls -la target/x86_64-unknown-linux-musl/release/ || true; \
     else \
     echo "Unsupported architecture: $(uname -m)" && exit 1; \
     fi
 
-# Create staging directory with binaries for final image
-RUN TARGET=$(cat /rust-photoacoustic/rust/_target) && \
-    mkdir -p /rust-photoacoustic/rust/release-staging && \
-    echo "Staging binaries from target: $TARGET" && \
-    for binary in analyze_spectrum create_token debug_config differential filters modbus_client noise_generator pid_tuner redis_viewer rs256keygen rust_photoacoustic; do \
-    if [ -f "/rust-photoacoustic/rust/target/$TARGET/release/$binary" ]; then \
-    echo "Copying $binary to staging" && \
-    cp "/rust-photoacoustic/rust/target/$TARGET/release/$binary" /rust-photoacoustic/rust/release-staging/ || true; \
-    fi; \
-    done && \
-    echo "Staging directory contents:" && \
-    ls -la /rust-photoacoustic/rust/release-staging/
+# # Create staging directory with binaries for final image
+# RUN TARGET=$(cat /rust-photoacoustic/rust/_target) && \
+#     mkdir -p /rust-photoacoustic/rust/release-staging && \
+#     echo "Staging binaries from target: $TARGET" && \
+#     for binary in analyze_spectrum create_token debug_config differential filters modbus_client noise_generator pid_tuner redis_viewer rs256keygen rust_photoacoustic; do \
+#     if [ -f "/rust-photoacoustic/rust/target/$TARGET/release/$binary" ]; then \
+#     echo "Copying $binary to staging" && \
+#     cp "/rust-photoacoustic/rust/target/$TARGET/release/$binary" /rust-photoacoustic/rust/release-staging/ || true; \
+#     fi; \
+#     done && \
+#     echo "Staging directory contents:" && \
+#     ls -la /rust-photoacoustic/rust/release-staging/
 
-# Clean up everything except the staging directory
-RUN rm -rf /root/.cargo && \
-    rm -rf /rust-photoacoustic/rust/target && \
-    rm -rf /tmp/* && \
-    echo "Build cleanup complete" 
+# # Clean up everything except the staging directory
+# RUN rm -rf /root/.cargo && \
+#     rm -rf /rust-photoacoustic/rust/target && \
+#     rm -rf /tmp/* && \
+#     echo "Build cleanup complete" 
 
 FROM alpine:3.23 AS runtime
 ARG PYTHON_VERSION=3.13.5
